image: ocaml/opam2

before_script:
  - sudo apt-get update -y && sudo apt-get install m4 -y

ocaml-4.02:
  script:
    - opam switch 4.02
    - eval $(opam env)
    - opam install ./ocolor.opam --deps-only -t
    - dune runtest
    - opam install ./ocolor.opam

ocaml-4.03:
  script:
    - opam switch 4.03
    - eval $(opam env)
    - opam install ./ocolor.opam --deps-only -t
    - dune runtest
    - opam install ./ocolor.opam

ocaml-4.04:
  script:
    - opam switch 4.04
    - eval $(opam env)
    - opam install ./ocolor.opam --deps-only -t
    - dune runtest
    - opam install ./ocolor.opam

ocaml-4.05:
  script:
    - opam switch 4.05
    - eval $(opam env)
    - opam install ./ocolor.opam --deps-only -t
    - dune runtest
    - opam install ./ocolor.opam

ocaml-4.06:
  script:
    - opam switch 4.06
    - eval $(opam env)
    - opam install ./ocolor.opam --deps-only -t
    - dune runtest
    - opam install ./ocolor.opam

ocaml-4.07:
  script:
    - opam switch 4.07
    - eval $(opam env)
    - opam install ./ocolor.opam --deps-only -t
    - dune runtest
    - opam install ./ocolor.opam

ocaml-4.08:
  script:
    - opam switch 4.08
    - eval $(opam env)
    - opam install ./ocolor.opam --deps-only -t
    - dune runtest
    - opam install ./ocolor.opam

